// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsfcyjriyawmudyzfygl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZmN5anJpeWF3bXVkeXpmeWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDkxODMsImV4cCI6MjA2MDE4NTE4M30.FJTVmUCta_Yl0nrq6SuDiKBZy1JCdNHrXn4kf4jZL3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);